### ISSUE TITLE
Composer 2.0 support

### ISSUE THREAD

**Issue by Levivb** [hirak/packagist-crawler#7]
Hey Hirak,

Are you planning on adding support for composer 2.0 which adds a `metadata-url` directive to packages.json which points composer to a `p2` directory with the packagist format: `/p2/%package%.json `

For example: https://packagist.org/p2/laravel/tinker.json

Background info:
https://github.com/composer/composer/blob/master/CHANGELOG.md
https://github.com/composer/composer/blob/master/UPGRADE-2.0.md#metadata-url

Regards,
Levi

**Comment by Seldaek** [comment]
Please use https://github.com/composer/mirror to create mirrors, it supports both v1 and v2 metadata and is battle tested syncing the official packagist.org mirrors.
